export const MODULE_CODES = {
  CABIN_QUALITY_AUDIT: 'CABIN_QUALITY_AUDIT',
  LAV_SAFETY_OBSERVATION: 'LAV_SAFETY_OBSERVATION',
  CABIN_SECURITY_SEARCH_TRAINING: 'CABIN_SECURITY_SEARCH_TRAINING',
  END_OF_SHIFT_REPORT: 'END_OF_SHIFT_REPORT',
  EMPLOYEE_ONE_ON_ONE: 'EMPLOYEE_ONE_ON_ONE',
  FEEDBACK: 'FEEDBACK',
  CHAT: 'CHAT',
  MASTER_DATA: 'MASTER_DATA',
  FILES: 'FILES',
  STATIONS: 'STATIONS',
} as const;

export type ModuleCode = (typeof MODULE_CODES)[keyof typeof MODULE_CODES];

export type PermissionAction = 'list' | 'view' | 'create';
